In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn import preprocessing


In [2]:
df=pd.read_csv('/content/Diabetes_microarray-2.csv')
df.head(5)
df.info()

<ipython-input-2-add901327193>:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/Diabetes_microarray-2.csv')


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Columns: 16383 entries, human islets to Status
dtypes: float64(16378), int64(1), object(4)
memory usage: 5.4+ MB


In [9]:
label_encoder = preprocessing.LabelEncoder()
df['ID_REF']= label_encoder.fit_transform(df['ID_REF'])
df['ID_REF'].unique()

df['Sex']= label_encoder.fit_transform(df['Sex'])
df['Sex'].unique()

label_encoder = preprocessing.LabelEncoder()
df['human islets']= label_encoder.fit_transform(df['human islets'])
df['human islets'].unique()

df['Status/hba1c'] = pd.to_numeric(df['Status/hba1c'], errors='coerce')
label_encoder = preprocessing.LabelEncoder()
df['Status/hba1c'] = label_encoder.fit_transform(df['Status/hba1c'])
df.head(5)


human islets  ID_REF  Sex  age   bmi  Status/hba1c   7896736   7896738  \
0             0       0    1   69  24.7             9  4.471944  2.379586   
1             9       1    1   56  24.7            19  4.912165  2.531345   
2            20       2    0   46  23.9             6  5.451896  1.927174   
3            31       3    0   62  27.7            19  4.144437  2.045959   
4            38       4    0   69  17.6            19  4.204524  2.275518   

    7896740   7896742  ...   8061171   8061184   8061186   8061211   8061222  \
0  2.639460  5.802042  ...  6.388191  5.528059   9.94582  8.257108  4.980597   
1  2.589392  5.811849  ...  6.742225  5.526723  10.19087  8.434197  5.115068   
2  3.068408  6.081089  ...  7.017448  5.649223  10.07701  8.213336  5.085982   
3  2.776792  6.282211  ...  6.872481  5.186767  10.00724  8.258103  4.895669   
4  2.999490  6.195026  ...  6.675658  5.943939  10.24777  8.144676  4.261562   

    8061224   8061227   8061247   8061262  Status  
0  2.714410  6.140991  7.999000  8.069311     0.0  
1  2.897943  6.234155  8.529483  8.937757     0.0  
2  2.731041  6.091517  8.507645  8.364843     0.0  
3  2.423555  5.960797  8.320624  8.179590     0.0  
4  2.675563  5.428856  7.880888  8.539515     0.0  

[5 rows x 16383 columns]

In [10]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.impute import SimpleImputer # import SimpleImputer

# Assuming 'df' is your DataFrame and 'Status/hba1c' is your target variable
X = df.drop('Status', axis=1)
y = df['Status']

# Impute missing values with the mean of each column
imputer = SimpleImputer(strategy='mean') # create an imputer instance
X = imputer.fit_transform(X) # impute missing values in X


# Impute missing values in the target variable 'y'
# You can use a strategy like 'most_frequent' or a constant value
imputer_y = SimpleImputer(strategy='most_frequent')  # Use 'most_frequent' for categorical target
y = imputer_y.fit_transform(y.values.reshape(-1, 1))  # Reshape for imputation
y = y.ravel()  # Flatten back to original shape


# Calculate the number of features representing 80%
num_features = int(0.8 * X.shape[1])

# Use SelectKBest with ANOVA F-value for feature selection
selector = SelectKBest(f_classif, k=num_features)
X_new = selector.fit_transform(X, y)

# Get the indices of the selected features
selected_feature_indices = selector.get_support(indices=True)

# Get the names of the selected features from the original DataFrame columns
selected_features = df.drop('Status', axis=1).columns[selected_feature_indices].tolist()


print("Top 80% features based on Fisher Score:")
print(selected_features)

# Create a new DataFrame with only the selected features
df_selected = df[selected_features]
df_selected['Status'] = y  # Add the target variable back

print("\nDataFrame with selected features:")
print(df_selected.head())

Top 80% features based on Fisher Score:
['human islets', 'ID_REF', 'bmi', 'Status/hba1c', '7896736', '7896738', '7896742', '7896744', '7896746', '7896752', '7896754', '7896756', '7896761', '7896817', '7896822', '7896859', '7896861', '7896863', '7896865', '7896878', '7896908', '7896917', '7896921', '7896929', '7896937', '7896952', '7896961', '7896983', '7896985', '7897006', '7897026', '7897044', '7897068', '7897089', '7897128', '7897132', '7897154', '7897172', '7897179', '7897210', '7897227', '7897236', '7897257', '7897263', '7897277', '7897286', '7897288', '7897293', '7897295', '7897329', '7897339', '7897368', '7897370', '7897378', '7897404', '7897416', '7897422', '7897426', '7897439', '7897441', '7897449', '7897460', '7897482', '7897520', '7897522', '7897527', '7897559', '7897632', '7897648', '7897661', '7897663', '7897675', '7897683', '7897685', '7897691', '7897714', '7897728', '7897737', '7897745', '7897753', '7897774', '7897801', '7897803', '7897824', '7897849', '7897877', '7897890

<ipython-input-10-c64363a31430>:41: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['Status'] = y  # Add the target variable back


In [14]:
# prompt: how to  store these  80% dataset in a excel sheet

# Convert the selected DataFrame to an Excel file
df_selected.to_excel('selected_features.xlsx', index=False)  # Save to 'selected_features.xlsx'

# Download the Excel file from Colab
from google.colab import files
files.download('selected_features.xlsx')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.feature_selection import SelectPercentile, f_classif
from sklearn.impute import SimpleImputer # import SimpleImputer
from google.colab import files
%matplotlib inline

# Assuming 'df' is your DataFrame and 'Status' is your target variable
X = df.drop('Status', axis=1)
y = df['Status']

# Impute missing values with the mean of each column
imputer = SimpleImputer(strategy='mean') # create an imputer instance
X = imputer.fit_transform(X) # impute missing values in X

# Impute missing values in the target variable 'y' using 'most_frequent'
# This is important as SelectPercentile cannot handle NaN values in 'y'
imputer_y = SimpleImputer(strategy='most_frequent')
y = imputer_y.fit_transform(y.values.reshape(-1, 1))
y = y.ravel() # Convert back to 1D array

# Use SelectPercentile with ANOVA F-value for feature selection
# Select top 60% of features
selector = SelectPercentile(f_classif, percentile=60)
X_new = selector.fit_transform(X, y)

# Get the indices of the selected features
selected_feature_indices = selector.get_support(indices=True)

# Get the names of the selected features
selected_features = df.drop('Status', axis=1).columns[selected_feature_indices].tolist()

print("Top 60% features based on Fisher Score:")
print(selected_features)

# Create a new DataFrame with only the selected features
df_selected = df[selected_features]
df_selected['Status'] = y  # Add the target variable back

print("\nDataFrame with selected features:")
print(df_selected.head())

# Convert the selected DataFrame to an Excel file
df_selected.to_excel('selected_features_60.xlsx', index=False)  # Save to 'selected_features_60.xlsx'

# Download the Excel file from Colab
files.download('selected_features_60.xlsx')

Top 60% features based on Fisher Score:
['ID_REF', 'bmi', 'Status/hba1c', '7896736', '7896738', '7896742', '7896744', '7896746', '7896752', '7896754', '7896756', '7896761', '7896859', '7896861', '7896865', '7896878', '7896908', '7896921', '7896929', '7896937', '7896961', '7896983', '7897026', '7897044', '7897068', '7897089', '7897128', '7897154', '7897172', '7897179', '7897210', '7897227', '7897236', '7897257', '7897263', '7897277', '7897286', '7897288', '7897295', '7897329', '7897370', '7897416', '7897422', '7897441', '7897449', '7897460', '7897520', '7897522', '7897527', '7897559', '7897648', '7897661', '7897663', '7897675', '7897683', '7897685', '7897691', '7897714', '7897728', '7897737', '7897745', '7897774', '7897824', '7897849', '7897890', '7897955', '7897964', '7897997', '7898002', '7898007', '7898026', '7898048', '7898057', '7898070', '7898084', '7898115', '7898161', '7898167', '7898176', '7898184', '7898192', '7898209', '7898249', '7898256', '7898278', '7898294', '7898314', '7

<ipython-input-15-9c70e9d62ea4>:41: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['Status'] = y  # Add the target variable back


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.feature_selection import SelectPercentile, f_classif
from sklearn.impute import SimpleImputer # import SimpleImputer
from google.colab import files
%matplotlib inline

# Assuming 'df' is your DataFrame and 'Status' is your target variable
X = df.drop('Status', axis=1)
y = df['Status']

# Impute missing values with the mean of each column
imputer = SimpleImputer(strategy='mean') # create an imputer instance
X = imputer.fit_transform(X) # impute missing values in X

# Impute missing values in the target variable 'y' using 'most_frequent'
# This is important as SelectPercentile cannot handle NaN values in 'y'
imputer_y = SimpleImputer(strategy='most_frequent')
y = imputer_y.fit_transform(y.values.reshape(-1, 1))
y = y.ravel() # Convert back to 1D array

# Use SelectPercentile with ANOVA F-value for feature selection
# Select top 40% of features
selector = SelectPercentile(f_classif, percentile=40)

#The error was caused by NaN values in the target variable 'y'.
#The following line imputes the missing values in 'y' before feature selection.
y = np.nan_to_num(y) # Replace NaN with 0

X_new = selector.fit_transform(X, y)

# Get the indices of the selected features
selected_feature_indices = selector.get_support(indices=True)

# Get the names of the selected features
selected_features = df.drop('Status', axis=1).columns[selected_feature_indices].tolist()

print("Top 40% features based on Fisher Score:")
print(selected_features)

# Create a new DataFrame with only the selected features
df_selected = df[selected_features]
df_selected['Status'] = y  # Add the target variable back

print("\nDataFrame with selected features:")
print(df_selected.head())

# Convert the selected DataFrame to an Excel file
df_selected.to_excel('selected_features_40.xlsx', index=False)

# Download the Excel file from Colab
files.download('selected_features_40.xlsx')

Top 40% features based on Fisher Score:
['ID_REF', 'bmi', 'Status/hba1c', '7896742', '7896744', '7896746', '7896754', '7896756', '7896761', '7896878', '7896921', '7896929', '7896937', '7896961', '7897044', '7897068', '7897128', '7897172', '7897227', '7897236', '7897286', '7897288', '7897295', '7897416', '7897449', '7897460', '7897520', '7897527', '7897648', '7897661', '7897663', '7897685', '7897691', '7897714', '7897745', '7897774', '7897824', '7897890', '7897964', '7897997', '7898002', '7898026', '7898057', '7898070', '7898084', '7898161', '7898167', '7898176', '7898184', '7898192', '7898249', '7898278', '7898294', '7898407', '7898413', '7898521', '7898535', '7898549', '7898556', '7898585', '7898655', '7898663', '7898673', '7898677', '7898713', '7898725', '7898732', '7898736', '7898809', '7898833', '7898854', '7898881', '7898939', '7898957', '7898975', '7898988', '7898998', '7899005', '7899018', '7899023', '7899029', '7899057', '7899087', '7899096', '7899124', '7899153', '7899167', '7

<ipython-input-16-3d2d215f7aac>:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['Status'] = y  # Add the target variable back


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
# prompt:  logistic regression model

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# Assuming df_selected is your DataFrame with selected features and 'Status' as the target
X = df_selected.drop('Status', axis=1)
y = df_selected['Status']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)  # Adjust test_size as needed

# Initialize and train the Logistic Regression model
logreg_model = LogisticRegression(max_iter=1000) # Increase max_iter if needed
logreg_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = logreg_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

print(classification_report(y_test, y_pred))

Accuracy: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00       0.0
           6       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_

In [ ]:
# prompt: using 80% features we apply Random Forest give me accuracy ,recall and f1 score

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

# Assuming 'fisher_scores', 'X', and 'y' are already defined from the previous code.

# Calculate the number of features to select (80%)
num_features = len(fisher_scores)
num_top_features = int(0.8 * num_features)

# Get indices of top features based on Fisher scores
top_feature_indices = np.argsort(fisher_scores)[::-1][:num_top_features]

# Select the top features
X_selected_80 = X.iloc[:, top_feature_indices]

# Impute missing values (if any)
imputer = SimpleImputer(strategy='mean')
X_selected_80 = imputer.fit_transform(X_selected_80)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_selected_80, y, test_size=0.2, random_state=42)

# Initialize and train a Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=42) # You can adjust hyperparameters here
rf_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = rf_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       1.0
           5       0.00      0.00      0.00       0.0
           6       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_

In [ ]:
# prompt: using 80% best  features we apply Decision tree give me accuracy ,recall and f1 score give me proper result

from sklearn.tree import DecisionTreeClassifier

# Assuming 'fisher_scores', 'X', and 'y' are already defined.

# Calculate the number of features to select (80%)
num_features = len(fisher_scores)
num_top_features = int(0.8 * num_features)

# Get indices of top features based on Fisher scores
top_feature_indices = np.argsort(fisher_scores)[::-1][:num_top_features]

# Select the top features
X_selected_80 = X.iloc[:, top_feature_indices]

# Impute missing values (if any)
imputer = SimpleImputer(strategy='mean')
X_selected_80 = imputer.fit_transform(X_selected_80)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_selected_80, y, test_size=0.2, random_state=42)

# Initialize and train a Decision Tree Classifier
dt_classifier = DecisionTreeClassifier(random_state=42) # You can adjust hyperparameters here
dt_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = dt_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       1.0
           3       0.00      0.00      0.00       0.0
           6       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_

In [ ]:
# prompt: using 60% best features we apply Logistic Regression give me accuracy ,recall and f1 score

# Assuming 'fisher_scores', 'X', and 'y' are already defined.

# Calculate the number of features to select (60%)
num_features = len(fisher_scores)
num_top_features = int(0.6 * num_features)

# Get indices of top features based on Fisher scores
top_feature_indices = np.argsort(fisher_scores)[::-1][:num_top_features]

# Select the top features
X_selected = X.iloc[:, top_feature_indices]

# Impute missing values (if any)
imputer = SimpleImputer(strategy='mean')
X_selected = imputer.fit_transform(X_selected)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)

# Initialize and train a Logistic Regression model
logreg = LogisticRegression(max_iter=1000)  # Increased max_iter
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       0.0
           2       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00       1.0
           5       0.00      0.00      0.00       0.0
           6       0.00      0.00      0.00       0.0
           8       0.00      0.00      0.00       0.0
          11       0.00      0.00      0.00       1.0
          13       0.00      0.00      0.00       0.0
          15       0.00      0.00      0.00       0.0
          17       0.00      0.00      0.00       0.0
          22       0.00      0.00      0.00       1.0
          27       0.00      0.00      0.00       1.0
          29       0.00      0.00      0.00       1.0
          40       0.00      0.00      0.00       1.0
          41       0.00      0.00      0.00       0.0
          42       0.00      0.00      0.00       1.0
          43 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_

In [ ]:


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
%matplotlib inline

# Assuming df is already loaded and preprocessed as in your original code
# ... (your code to load and preprocess df) ...

# Feature Selection Percentages to try
percentages = [0.8, 0.6, 0.4]

for percentage in percentages:
    # Calculate the number of features to select
    num_features = len(fisher_scores)
    num_top_features = int(percentage * num_features)

    # Get indices of top features
    top_feature_indices = np.argsort(fisher_scores)[::-1][:num_top_features]
    top_features = X.columns[top_feature_indices]

    print(f"\nTop {num_top_features} features ({percentage * 100:.0f}%): {top_features}")


    # Feature selection and imputation
    X_selected = X.iloc[:, top_feature_indices]
    imputer = SimpleImputer(strategy='mean')
    X_selected = imputer.fit_transform(X_selected)

    # Train test split
    X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)

    # Logistic Regression
    logreg = LogisticRegression(max_iter=1000)
    logreg.fit(X_train, y_train)
    y_pred = logreg.predict(X_test)
    print("\n---Logistic Regression---")
    print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

    # Random Forest Classifier
    rf_classifier = RandomForestClassifier(random_state=42)
    rf_classifier.fit(X_train, y_train)
    y_pred_rf = rf_classifier.predict(X_test)
    print("\n---Random Forest Classifier---")
    print(f"Accuracy: {accuracy_score(y_test, y_pred_rf)}")
    print(classification_report(y_test, y_pred_rf))
    print(confusion_matrix(y_test, y_pred_rf))

    # Decision Tree Classifier
    dt_classifier = DecisionTreeClassifier(random_state=42)
    dt_classifier.fit(X_train, y_train)
    y_pred_dt = dt_classifier.predict(X_test)
    print("\n---Decision Tree Classifier---")
    print(f"Accuracy: {accuracy_score(y_test, y_pred_dt)}")
    print(classification_report(y_test, y_pred_dt))
    print(confusion_matrix(y_test, y_pred_dt))


Top 12148 features (80%): Index(['8061272', '8047006', '8046804', '8046815', '8046822', '8046824',
       '8046833', '8046836', '8046848', '8046861',
       ...
       '7982574', '7982564', '7982552', '7982550', '7982535', '7982533',
       '7982531', '7982529', '7982527', '7982292'],
      dtype='object', length=12148)

---Logistic Regression---
Accuracy: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00       0.0
           6       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_


---Random Forest Classifier---
Accuracy: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       1.0
           5       0.00      0.00      0.00       0.0
           6       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]

---Decision Tree Classifier---
Accuracy: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       1.0
           3       0.00      0.00      0.00       0.0
           6       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00     

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_


---Logistic Regression---
Accuracy: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       1.0
           6       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

[[0 0 1]
 [0 0 1]
 [0 0 0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_


---Random Forest Classifier---
Accuracy: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       1.0
           6       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

[[0 0 1]
 [0 0 1]
 [0 0 0]]

---Decision Tree Classifier---
Accuracy: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       1.0
           3       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

[[0 0 1]
 [0 0 1]
 [0 0 0]]

Top 6074 features (40%): Index(['8061272', '8047006', '8046804', '8046815', '8046822', '8

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_


---Logistic Regression---
Accuracy: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       1.0
           6       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

[[0 0 1]
 [0 0 1]
 [0 0 0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_


---Random Forest Classifier---
Accuracy: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       1.0
           6       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

[[0 0 1]
 [0 0 1]
 [0 0 0]]

---Decision Tree Classifier---
Accuracy: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

[[0 0 1]
 [0 0 1]
 [0 0 0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_